<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="topbar">
    <div class="fill">
        <div class="container">
            <a class="brand" href="<?php echo $this->getUrl('') ?>"><?php echo $this->getLogoAlt() ?></a>
            <?php echo $this->getChildHtml('topSearch') ?>
        </div>
    </div>
</div>

<?php echo $this->getChildHtml('topContainer'); ?>
<!--<p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>-->
<?php //echo $this->getChildHtml('store_language') ?>
<?php echo $this->getChildHtml('topMenu') ?>
