<!--
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get" class="pull-right">
    <input class="input-small" id="search" type="text" placeholder="<?php echo $this->__('Search') ?>" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>">
    <button class="btn" type="submit"><?php echo $this->__('Search') ?></button>
</form>
-->