<ul class="nav secondary-nav">
    <li>
        <a data-controls-modal="modal-from-dom" data-backdrop="true" data-keyboard="true" href="#">Add Your Twitter Account</a>
    </li>
</ul>

<div id="modal-from-dom" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h3>Add Your Twitter Account</h3>
    </div>
    <div class="modal-body">

        <p>Add your twitter handle below.</p>
        <form id='username_add' action="" class="form-stacked">
            <fieldset>
                <div class="clearfix">
                    <label for="username">Twitter Username</label>
                    <div class="input">
                        <input id="username" name="username" size="30" type="text" />
                    </div>
                </div><!-- /clearfix -->
            </fieldset></fieldset>
        </form>

    </div>
    <div class="modal-footer">
        <a href="#" onClick="javascript:$('#username_add').submit();" class="btn primary">Add Now</a>
    </div>
</div>

