<?php if (!$this->getAccounts()->count()): ?>
    None found
<?php else: ?>
    <table class="bordered-table zebra-striped">
        <thead>
        <tr>
            <th>Score</th>
            <th>Username</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getAccounts() as $account): ?>
            <tr>
                <td width="15%" style="line-height: 25px; height: 22px; padding-bottom: 0px;">-<?php echo $account->getPoints(); ?></td>
                <td style="line-height: 25px; height: 22px; padding-bottom: 0px;">
                    <?php echo $this->getHtmlImageTag($account); ?>
                    &nbsp;@<?php echo $account->getUsername(); ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
