<div class="row">
    <div class="span8">
        <h4>Trending Twumbags</h4>
        <table class="bordered-table zebra-striped">
            <thead>
            <tr>
                <th>Points</th>
                <th>Username</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>-3</td>
                <td>@somecrazyguy</td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="span8">
        <h4>Trending Twumhunters</h4>
        <table class="bordered-table zebra-striped">
            <thead>
            <tr>
                <th>Points</th>
                <th>Username</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>-3</td>
                <td>@somecrazyguy</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
